### ISSUE TITLE
Entropy module has no attribute 'perm_entropy'

### ISSUE THREAD

**Issue by jmkendallbar** [raphaelvallat/entropy#13]
When trying to run the Sleep Staging prediction code below, on my own .EDF dataset, I get the same entropy error that the module 'entropy' has no attribute 'perm_entropy'. I was able to import my dataset and print out summary statistics for my dataset, but am getting stuck here. Please let me know what troubleshooting I can try. Thanks!

 `sls = yasa.SleepStaging(raw, eeg_name="LEEG3_Ch12", eog_name="LEOG_Ch2", emg_name="LEMG_Ch5", metadata=dict(age=1.8, male=False))

# Getting the predicted sleep stages is now as easy as:
y_pred = sls.predict()`

AttributeError: module 'entropy' has no attribute 'perm_entropy'

**Comment by raphaelvallat** [comment]
Hi @jmkendallbar,

Most likely this is because you don't have the "correct" entropy package. As explained in the docs, there is already a package called "entropy", meaning that unfortunately, the current package cannot be installed using `pip install entropy`. Can you try the following lines in a terminal:

```
pip uninstall entropy
git clone https://github.com/raphaelvallat/entropy.git entropy/
cd entropy/
pip install -r requirements.txt
python setup.py develop
```

Thanks
Raphael

**Comment by jmkendallbar** [comment]
This worked perfectly, thank you very much.
