### ISSUE TITLE
Sample entropy returns inf

### ISSUE THREAD

**Issue by Gongxter** [raphaelvallat/entropy#9]
Hi,
Somehow when I try to calculate the sample entropy of a series it returns me inf.
I couldn't find anything about this in the documentation.

this is a dataset which leads to inf sample entropy with Chebyshev distance and order= 2:

[0, 4, 3, 1, 0, 4, 1, 9, 6, 0, 4, 6, 4, 3, 8, 8, 3, 5, 6, 6, 1, 6, 5, 2, 0, 6, 7, 6, 5, 8, 5, 2, 5, 5, 0, 0, 8, 5, 8, 9, 3, 5, 3, 6, 8, 4, 6, 5, 4, 5, 7]

Might this be because the dataset is too small ?

**Comment by raphaelvallat** [comment]
Hi @Gongxter,

Indeed, this is very much likely caused by a too sample size (which leads to a division by zero and then -np.log(0) = inf). I don't know exactly what would be a minimum number of samples to calculate a reliable sample entropy though. Perhaps worth adding a warning when users try to calculate the sample entropy with less than, say, 100 samples.

Thanks,
Raphael

**Comment by Gongxter** [comment]
Hi @raphaelvallat, 

Thanks for the clarification.

Best regards,

Timm
